# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
  - stage: GCP_TF_deploy
    #displayname: "Planning GCP resources using TF"
    jobs:
      - job: planning_tf
        pool: 
          name: 'Azure pipeline'
          vmImage: 'Windows latest'
        steps:
          - task: TerraformInstaller@1
            inputs:
             terraformVersion: 'latest'
          - task: TerraformCLI@0
            displayName: 'Initilizing Terraform'
            env:
              Google_credentials: $(Google_credentials)
              Billing_Ac_Id: $(Billing_ac_id)
            inputs:
                 command: 'init'
           
          - task: PowerShell@2
            inputs:
             targetType: 'inline'
             script: |
               # Write your PowerShell commands here.
      
                 terraform plan -v project_id=$env:project_id -v Billing_Ac_Id=$env:Billing_ac_id
